# -*- coding: utf-8 -*-
"""pdf_des

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDkiUy05J7JtvD5kmBEzodsk0ekzzeI-
"""

import streamlit as st
import fitz  # PyMuPDF
from openpyxl import load_workbook
import requests
import tempfile

# PDFからテキストを抽出する関数
def extract_text_from_pdf(pdf_file, rects):
    str_data = []
    labels = []

    # Streamlitでアップロードされたファイルを一時ファイルとして保存
    with fitz.open(stream=pdf_file.read(), filetype="pdf") as doc:
        for rect_data in rects:
            x0, y0, x1, y1, label = rect_data
            rect = fitz.Rect(x0, y0, x1, y1)
            labels.append(label)
            text = ""
            for page in doc:
                extracted_text = page.get_text("text", clip=rect)
                text += extracted_text.strip() if extracted_text.strip() else ""
            str_data.append(text)
    return str_data, labels

# StreamlitによるGUI
def main(uploaded_file):
    st.title("伝票作成アプリ")

    # PDFアップロード
    if uploaded_file:
        st.success(f"{uploaded_file.name} がアップロードされました")

        # 抽出範囲の指定
        rects = [
            (140, 175, 180, 190, 'AC9-1'),
            (140, 190, 180, 205, 'AC9'),
            (210, 190, 500, 205, 'AC11'),
            (140, 205, 180, 220, 'AC13'),
            (210, 205, 500, 220, 'AC15'),
            (100, 215, 140, 230, 'AC17'),
            (135, 220, 500, 230, 'AC19'),
            (105, 295, 250, 305, 'A11'),
            (400, 360, 500, 370, 'S11')
        ]

        # テキスト抽出
        str_data, labels = extract_text_from_pdf(uploaded_file, rects)
        st.write("抽出されたテキスト:")
        for label, text in zip(labels, str_data):
            st.write(f"**{label}**: {text}")

        # ユーザー入力
        syukka = st.date_input("出荷日を入力してください")
        buturyu = st.selectbox("物流センターを選択してください",['AX44', 'AX60', 'AX02','AX36','AX86','AX28'])
        konpou = st.selectbox("梱包数を選択してください",['1','2','3','4','5','それ以上'])
        if konpou =='それ以上':
            konpou = st.text_input('梱包数を入力してください')

        # Excel更新
        if st.button("Excelファイルを生成する"):
            # GitHubのリポジトリURL
            import shutil
            github_url = "https://github.com/shintarotakasaki/excel3/raw/main/伝票(規格品)_ラベル_指示書.xlsm"

            # ファイルをダウンロードして一時ファイルとして保存
            response = requests.get(github_url,stream=True)
            if response.status_code == 200:
                file_path = "伝票(規格品)_ラベル_指示書.xlsm"  # ここで file_path を定義
                with open("伝票(規格品)_ラベル_指示書.xlsm",'wb')as f:
                    response.raw.decode_content = True
                    shutil.copyfileobj(response.raw, f)

            try:
                wb = load_workbook(file_path, keep_vba=True)
                ws = wb['納品書控(製品)']
                wb.active = ws

                # Excelファイルへの書き込み
                ws['AH3'] = syukka
                ws['AM9'] = buturyu
                ws['AB4'] = konpou + "梱包"

                zig_tok = ""
                for i, text in enumerate(str_data):
                    if labels[i] == 'AC9-1':
                        zig_tok = text
                    elif labels[i] == 'AC9':
                        ws[labels[i]] = zig_tok + '-' + text
                    elif labels[i] == 'AC11':
                        ws[labels[i]] = text + "様"
                    elif labels[i] == 'AC13':
                        ws[labels[i]] = '届け先：' + text
                    elif labels[i] == 'AC15':
                        ws[labels[i]] = text + "様" if text else "=AC11"
                    elif labels[i] == 'AC17':
                        ws[labels[i]] = '現場名：' + text
                    else:
                        ws[labels[i]] = text

                # 保存とダウンロード
                wb.save(file_path)
                st.success("Excelファイルが上書き保存されました！")

                #ファイルをダウンロード
                st.write("保存されたファイルを以下のリンクからダウンロードしてください:")
                with open(file_path, "rb") as file:
                    st.download_button(
                        label="ダウンロードする",
                        data=file,
                        file_name="伝票(規格品)_ラベル_指示書.xlsm",
                        mime="application/vnd.ms-excel"
                    )
            except Exception as e:
                st.error(f"エラーが発生しました: {e}")

if __name__ == "__main__":
    main()
Excel版のスクリプト
# -*- coding: utf-8 -*-
"""after_xl_scr
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1b3VXkHSUL8qaZE8LvrnmW17Nh3gh3TGN
"""

from openpyxl import load_workbook
import streamlit as st
from io import BytesIO
import requests
import shutil

# コメントアウトされたコード

def xl_data_upload(uploaded_file):
    str_data = []

    #after_xl = st.file_uploader("アフター申請書エクセルをアップロードしてください")

    if uploaded_file is not None:
        file_mime = uploaded_file.type
        if file_mime == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
            try:
                file = BytesIO(uploaded_file.getvalue())
                wb = load_workbook(filename=file)
                sheet = wb.active
                rects = ["G19","G20","L15","N20","G21","N21","G23","Q23","H28","AB34"]

                for rect in rects:
                    str_data.append(sheet[rect].value)

                for rect, value in zip(rects, str_data):
                    st.write(f"{rect}: {value}")

                return str_data

            except Exception as e:
                st.error(f"エラーが発生しました: {e}")
                return None

        else:
            st.write("エクセルファイル(.xlsx)をアップロードしてください")
            st.stop()


def main (uploaded_file):
    """
    GitHubからExcelファイルをダウンロードし、開く関数。
    """
    str_data = ""
    xlpoints = ["AC9-1","AC9","AM9","AC11","AC13","AC15","AC19-1","AC19","A11","S11"]

    #after_xl = st.file_uploader("アフター申請書エクセルをアップロードしてください")

    if uploaded_file is not None:
        str_data = xl_data_upload(uploaded_file)

    else:
        st.write("エクセルファイル(.xlsx)をアップロードしてください")
        st.stop()

    genba = "現場名："
    syukka = st.date_input("出荷日を入力してください")
    konpou = st.selectbox("梱包数を選択してください",['1','2','3','4','5','それ以上'])
    if konpou =='それ以上':
        konpou = st.text_input('梱包数を入力してください(半角数字)')

    if st.button("Excelファイルを生成する"):
        github_url = "https://github.com/shintarotakasaki/excel3/raw/main/伝票(規格品)_ラベル_指示書.xlsm"
        # ファイルをダウンロードして一時ファイルとして保存
        response = requests.get(github_url,stream=True)
        if response.status_code == 200:
            file_path = "伝票(規格品)_ラベル_指示書.xlsm"  # ここで file_path を定義
            with open("伝票(規格品)_ラベル_指示書.xlsm",'wb')as f:
                response.raw.decode_content = True
                shutil.copyfileobj(response.raw, f)

        try:
            wb_demp = load_workbook(file_path, keep_vba=True)
            ws_demp = wb_demp['納品書控(製品)']
            wb_demp.active = ws_demp